/** Complete musical scenes for both articulated forms.
 * Kept independent of hand-model.js: the model injects normalization and pose
 * helpers after its own defaults exist, avoiding a circular module dependency.
 * Existing musical settings stay intact; appearance and menu order may change.
 */
const PRESET_DEFINITIONS = [
  ["glass-wave", "Glass greeting", "open", "wave", 67, .72, 181, .44, .06, .42, .04, .85, ["glass", "glass", "glass", "wire", "air"]],
  ["reed-beckon", "Come closer", "relaxed", "beckon", 79, .82, 101, .55, .22, .16, .024, .25, ["reed", "reed", "wire", "reed", "air"]],
  ["wire-roll", "Finger loom", "relaxed", "finger-roll", 104, .77, 83, .69, .3, .33, .01, .32, ["wire", "wire", "wire", "wire", "glass"]],
  ["pinch-sparks", "Pinch sparks", "open", "pinch", 92, .9, 226, .72, .19, .12, .008, .13, ["pulse", "glass", "wire", "air", "glass"]],
  ["counting-air", "Count the air", "open", "count", 131, .88, 149, .27, .09, .68, .22, 1.1, ["air", "reed", "air", "glass", "air"]],
  ["flourish-copper", "Copper flourish", "fan", "flourish", 61, .8, 119, .74, .52, .46, .07, .65, ["wire", "reed", "pulse", "wire", "reed"]],
  ["low-claw", "Velvet claw", "claw", "finger-roll", 38, .33, 48, .17, .12, .2, .34, 1.4, ["reed", "pulse", "reed", "wire", "air"]],
  ["hushed-palm", "Hushed palm", "open", "wave", 29, .54, 312, .16, .02, .82, .65, 2.2, ["air", "glass", "air", "air", "glass"]],
  ["point-transmission", "Point transmission", "point", "flourish", 157, .38, 73, .86, .65, .06, .004, .085, ["pulse", "pulse", "wire", "pulse", "reed"]],
  ["slow-unfurl", "Slow unfurl", "relaxed", "count", 49, .66, 207, .39, .27, .59, .48, 1.75, ["glass", "wire", "reed", "air", "glass"]],
  ["closed-bell", "Bell in a fist", "fist", "still", 88, 0, 63, .61, .08, .37, .018, 1.3, ["glass", "glass", "glass", "glass", "glass"]],
  ["little-machinery", "Little machinery", "pinch", "beckon", 186, .48, 126, .81, .81, .23, .006, .17, ["pulse", "wire", "reed", "pulse", "air"]],
  ["original-grasp", "Original grasp", "source-open", "source-grasp", 75, 1, 151, .49, .13, .3, .04, .58, ["glass", "wire", "reed", "glass", "air"]],
  ["breathing-hand", "Breathing hand", "source-open", "source-grasp", 34, 1, 79, .24, .06, .71, .38, 1.8, ["air", "reed", "air", "wire", "air"]],
  ["bowed-spiral", "Rosin spiral", "source-open", "flourish-spiral", 74, .82, 92, .51, .37, .48, .16, .93, ["bowed", "bowed", "wire", "bowed", "glass"], .65],
  ["vowel-opposition", "Talking fingertips", "source-open", "opposition-walk", 89, .91, 118, .63, .21, .21, .032, .38, ["vowel", "vowel", "reed", "vowel", "air"], 1.1],
  ["metal-drumming", "Tin fingernails", "source-open", "finger-drumming", 122, .92, 173, .83, .47, .17, .006, .22, ["metal", "metal", "wire", "metal", "pulse"], 1.4],
  ["bowed-eight", "Cello figure eight", "relaxed", "figure-eight", 51, .68, 57, .28, .18, .56, .31, 1.65, ["bowed", "reed", "bowed", "bowed", "air"], .45],
  ["vowel-fan", "Palm choir", "source-open", "finger-fan", 62, .95, 204, .34, .08, .74, .44, 1.9, ["vowel", "vowel", "air", "vowel", "glass"], .8],
  ["metal-walk", "Clockwork fingers", "source-open", "two-finger-walk", 111, .76, 81, .71, .61, .29, .009, .31, ["metal", "pulse", "metal", "wire", "metal"], 1.7],
  ["tangled-polyrhythm", "Polyrhythmic tangle", "source-open", "polyrhythmic-tangle", 610, .86, 97, .67, .34, .29, .014, .21, ["wire", "metal", "vowel", "bowed", "glass"], 1.7],
  ["swarming-fingers", "Finger swarm", "source-open", "finger-swarm", 820, .78, 71, .75, .41, .22, .007, .15, ["pulse", "wire", "metal", "pulse", "air"], 2.4],
  ["orbit-frenzy", "Frantic orbit", "source-open", "frantic-orbit", 1060, .88, 113, .57, .49, .18, .009, .18, ["vowel", "bowed", "metal", "wire", "pulse"], 2.8],
  ["scattered-sparks", "Scattered sparks", "source-open", "scatter", 950, .93, 188, .86, .62, .13, .004, .09, ["metal", "pulse", "glass", "metal", "wire"], 3.1],
];
// Camera choices belong to full scenes; omitted entries retain the palm view.
const PRESET_VIEWS = {
  "reed-beckon": { yaw: -.65, pitch: .12, zoom: 1.05 },
  "wire-roll": { yaw: .75, pitch: -.12, zoom: 1.06 },
  "pinch-sparks": { yaw: -.9, pitch: .2, zoom: 1.15 },
  "flourish-copper": { yaw: .45, pitch: -.3, zoom: .88 },
  "low-claw": { yaw: 1.18, pitch: .15, zoom: 1 },
  "hushed-palm": { yaw: -.15, pitch: .16, zoom: .92 },
  "point-transmission": { yaw: -1.1, pitch: .06, zoom: 1.05 },
  "closed-bell": { yaw: .9, pitch: .25, zoom: 1.12 },
  "vowel-opposition": { yaw: -.7, pitch: .13, zoom: 1.1 },
  "metal-drumming": { yaw: 1.08, pitch: -.28, zoom: 1 },
  "bowed-eight": { yaw: 2.5, pitch: -.08, zoom: .92 },
  "metal-walk": { yaw: -1.15, pitch: .15, zoom: 1.06 },
  "tangled-polyrhythm": { yaw: -.45, pitch: .25, zoom: .9 },
  "swarming-fingers": { yaw: 1.32, pitch: .05, zoom: .88 },
  "orbit-frenzy": { yaw: -2.2, pitch: -.12, zoom: .82 },
  "scattered-sparks": { yaw: .7, pitch: .34, zoom: .92 },
};
const PRESET_TREMORS = {
  "reed-beckon": { finger: "thumb", joint: "knuckle", amount: 2.2, rate: 4.7 },
  "glass-wave": { finger: "all", joint: "tip", amount: 1.6, rate: 5.8 },
  "bowed-spiral": { finger: "alternating", joint: "whole", amount: 1.9, rate: 6.4 },
  "vowel-opposition": { finger: "index", joint: "middle", amount: 3.2, rate: 7.8 },
  "metal-drumming": { finger: "ring", joint: "tip", amount: 4, rate: 13 },
  "bowed-eight": { finger: "all", joint: "tip", amount: 1.2, rate: 5.2 },
  "tangled-polyrhythm": { finger: "alternating", joint: "whole", amount: 2.8, rate: 17 },
  "swarming-fingers": { finger: "alternating", joint: "tip", amount: 6.2, rate: 27 },
  "orbit-frenzy": { finger: "all", joint: "wrist", amount: 4.5, rate: 12 },
  "scattered-sparks": { finger: "little", joint: "middle", amount: 8, rate: 33 },
};
const PRESET_APPEARANCES = {
  "glass-wave": { skin: "copper", lighting: "cool" },
  "reed-beckon": { skin: "copper", lighting: "warm" },
  "wire-roll": { skin: "copper", lighting: "studio" },
  "pinch-sparks": { skin: "cyan", lighting: "neon" },
  "counting-air": { skin: "violet", lighting: "soft" },
  "flourish-copper": { skin: "copper", lighting: "warm" },
  "low-claw": { skin: "jade", lighting: "noir" },
  "hushed-palm": { skin: "copper", lighting: "soft" },
  "point-transmission": { skin: "cyan", lighting: "cool" },
  "closed-bell": { skin: "copper", lighting: "warm" },
  "tangled-polyrhythm": { skin: "jade", lighting: "neon" },
  "swarming-fingers": { skin: "violet", lighting: "cool" },
  "orbit-frenzy": { skin: "cyan", lighting: "neon" },
  "scattered-sparks": { skin: "copper", lighting: "noir" },
};
const PRESET_ROTATION_FX = {
  "glass-wave": .68, "reed-beckon": .42, "wire-roll": .76, "pinch-sparks": .54,
  "counting-air": .38, "flourish-copper": .92, "low-claw": .34, "hushed-palm": .28,
  "point-transmission": .81, "slow-unfurl": .57, "closed-bell": .18, "little-machinery": .72,
  "original-grasp": .65, "breathing-hand": .31, "bowed-spiral": .86, "vowel-opposition": .46,
  "metal-drumming": .61, "bowed-eight": .78, "vowel-fan": .43, "metal-walk": .74,
  "tangled-polyrhythm": .88, "swarming-fingers": .71, "orbit-frenzy": 1, "scattered-sparks": .83,
};
const FOOT_PRESET_DEFINITIONS = [
  { id: "foot-velvet-curl", label: "Velvet toe curl", pose: "source-open", motion: { id: "source-grasp", tempo: 58, amount: .92, speed: .8 },
    sound: { rootHz: 73, brightness: .4, roughness: .18, space: .4, rotationFx: .58, attack: .08, release: .72 },
    sources: ["bowed", "reed", "wire", "bowed", "air"], appearance: { skin: "copper", lighting: "warm" }, view: { yaw: -.35, pitch: .2, zoom: 1 },
    tremor: { finger: "thumb", joint: "tip", amount: 1.4, rate: 4.3 } },
  { id: "foot-glass-ripple", label: "Glass toe ripple", pose: "open", motion: { id: "ripple-open", tempo: 83, amount: .85, speed: 1.1 },
    sound: { rootHz: 193, brightness: .54, roughness: .09, space: .65, rotationFx: .74, attack: .035, release: .93 },
    sources: ["glass", "vowel", "glass", "wire", "air"], appearance: { skin: "cyan", lighting: "cool" }, view: { yaw: .62, pitch: -.12, zoom: 1.05 },
    tremor: { finger: "alternating", joint: "tip", amount: 2.1, rate: 6.7 } },
  { id: "foot-tin-drumming", label: "Tin toe drumming", pose: "source-open", motion: { id: "finger-drumming", tempo: 151, amount: 1, speed: 1.6 },
    sound: { rootHz: 121, brightness: .78, roughness: .48, space: .19, rotationFx: .83, attack: .006, release: .2 },
    sources: ["metal", "pulse", "metal", "wire", "metal"], appearance: { skin: "copper", lighting: "studio" }, view: { yaw: -.8, pitch: .3, zoom: .96 },
    tremor: { finger: "little", joint: "knuckle", amount: 2.6, rate: 11 } },
  { id: "foot-ankle-orbit", label: "Ankle choir", pose: "relaxed", motion: { id: "figure-eight", tempo: 47, amount: .95, speed: .6 },
    sound: { rootHz: 97, brightness: .33, roughness: .14, space: .73, rotationFx: .95, attack: .26, release: 1.5 },
    sources: ["vowel", "bowed", "vowel", "reed", "air"], appearance: { skin: "violet", lighting: "soft" }, view: { yaw: 1.15, pitch: .08, zoom: .9 },
    tremor: { finger: "all", joint: "wrist", amount: 1.7, rate: 3.4 } },
];
const ADDED_SCENES = [
  { id: "hand-silk-count", label: "Silk abacus", form: "hand", pose: "open", motion: { id: "count", tempo: 46, amount: .46, speed: .55 },
    sound: { rootHz: 167, brightness: .22, roughness: .04, space: .62, rotationFx: .35, attack: .32, release: 1.8 },
    sources: ["glass", "wire", "air", "glass", "bowed"], levels: [.69, .54, .44, .61, .56],
    appearance: { skin: 0.56, lighting: 0.92 }, view: { yaw: .24, pitch: .21, zoom: .95 }, tremor: { finger: "all", joint: "tip", amount: .12, rate: .34 } },
  { id: "hand-copper-shiver", label: "Copper shiver", form: "hand", pose: "pinch", motion: { id: "finger-scissors", tempo: 148, amount: .82, speed: 2.7 },
    sound: { rootHz: 113, brightness: .84, roughness: .62, space: .11, rotationFx: .92, attack: .008, release: .13 },
    sources: ["metal", "pulse", "wire", "metal", "reed"], levels: [.64, .55, .73, .58, .52],
    appearance: { skin: 0.08, lighting: 0.76 }, view: { yaw: -.88, pitch: -.26, zoom: .87 }, tremor: { finger: "alternating", joint: "middle", amount: 7.8, rate: 19 } },
  { id: "hand-paper-waltz", label: "Paper waltz", form: "hand", pose: "relaxed", motion: { id: "wrist-circle", tempo: 84, amount: .57, speed: 1.15 },
    sound: { rootHz: 261, brightness: .31, roughness: .06, space: .47, rotationFx: .68, attack: .18, release: .8 },
    sources: ["vowel", "air", "reed", "vowel", "wire"], levels: [.67, .39, .64, .6, .53],
    appearance: { skin: 0.17, lighting: 0.34 }, view: { yaw: .72, pitch: .13, zoom: .91 }, tremor: { finger: "all", joint: "tip", amount: .45, rate: 4 } },
  { id: "hand-radio-swarm", label: "Radio swarm", form: "hand", pose: "claw", motion: { id: "finger-swarm", tempo: 417, amount: .73, speed: 2.2 },
    sound: { rootHz: 64, brightness: .92, roughness: .85, space: .08, rotationFx: .89, attack: .004, release: .08 },
    sources: ["pulse", "pulse", "metal", "wire", "vowel"], levels: [.58, .52, .72, .61, .57],
    appearance: { skin: 0.64, lighting: 0.63 }, view: { yaw: 1.4, pitch: -.18, zoom: .81 }, tremor: { finger: "alternating", joint: "whole", amount: 9.2, rate: 31 } },
  { id: "hand-bowed-tide", label: "Bowed tide", form: "hand", pose: "source-open", motion: { id: "flourish-spiral", tempo: 39, amount: .68, speed: .7 },
    sound: { rootHz: 53, brightness: .19, roughness: .1, space: .76, rotationFx: .76, attack: .48, release: 2.3 },
    sources: ["bowed", "bowed", "reed", "bowed", "air"], levels: [.71, .63, .57, .65, .42],
    appearance: { skin: 0.33, lighting: 0.16 }, view: { yaw: -1.22, pitch: .28, zoom: .9 }, tremor: { finger: "all", joint: "whole", amount: 0, rate: 1.4 } },
  { id: "hand-porcelain-flicker", label: "Porcelain flicker", form: "hand", pose: "open", motion: { id: "flick", tempo: 176, amount: .87, speed: 2.4 },
    sound: { rootHz: 331, brightness: .73, roughness: .08, space: .29, rotationFx: .57, attack: .006, release: .25 },
    sources: ["glass", "metal", "glass", "wire", "glass"], levels: [.61, .46, .7, .57, .54],
    appearance: { skin: 0.79, lighting: 0.04 }, view: { yaw: .49, pitch: -.32, zoom: .96 }, tremor: { finger: "index", joint: "knuckle", amount: .6, rate: 9.4 } },
  { id: "hand-throat-lattice", label: "Throat lattice", form: "hand", pose: "pinch", motion: { id: "opposition-walk", tempo: 112, amount: .9, speed: 1.4 },
    sound: { rootHz: 89, brightness: .66, roughness: .31, space: .33, rotationFx: .44, attack: .075, release: .4 },
    sources: ["vowel", "vowel", "vowel", "reed", "air"], levels: [.64, .6, .72, .55, .37],
    appearance: { skin: 0.87, lighting: 0.23 }, view: { yaw: -.58, pitch: .32, zoom: 1.08 }, tremor: { finger: "thumb", joint: "knuckle", amount: 4.6, rate: 7.1 } },
  { id: "hand-held-current", label: "Held current", form: "hand", pose: "fan", motion: { id: "still", tempo: 60, amount: 0, speed: 1 },
    sound: { rootHz: 197, brightness: .43, roughness: .23, space: .58, rotationFx: .96, attack: .22, release: 1.45 },
    sources: ["air", "wire", "bowed", "vowel", "glass"], levels: [.41, .61, .68, .6, .5],
    appearance: { skin: 0.51, lighting: 0.96 }, view: { yaw: 2.12, pitch: -.11, zoom: 1.02 }, tremor: { finger: "all", joint: "wrist", amount: 6.2, rate: 3.9 } },
  { id: "hand-tin-morse", label: "Tin Morse", form: "hand", pose: "claw", motion: { id: "finger-drumming", tempo: 233, amount: .95, speed: 3.1 },
    sound: { rootHz: 227, brightness: .88, roughness: .71, space: .12, rotationFx: .63, attack: .004, release: .075 },
    sources: ["metal", "metal", "pulse", "metal", "wire"], levels: [.67, .57, .55, .72, .51],
    appearance: { skin: 0.03, lighting: 0.45 }, view: { yaw: -1.65, pitch: .17, zoom: .86 }, tremor: { finger: "ring", joint: "tip", amount: 4.3, rate: 13.6 } },
  { id: "hand-velvet-scissors", label: "Velvet scissors", form: "hand", pose: "fan", motion: { id: "finger-scissors", tempo: 64, amount: .53, speed: .9 },
    sound: { rootHz: 102, brightness: .28, roughness: .07, space: .52, rotationFx: .32, attack: .24, release: 1.3 },
    sources: ["reed", "wire", "bowed", "air", "reed"], levels: [.6, .58, .7, .4, .56],
    appearance: { skin: 0.41, lighting: 0.58 }, view: { yaw: .34, pitch: .27, zoom: 1.11 }, tremor: { finger: "little", joint: "tip", amount: .2, rate: .83 } },
  { id: "hand-five-way-stumble", label: "Five-way stumble", form: "hand", pose: "relaxed", motion: { id: "polyrhythmic-tangle", tempo: 269, amount: .79, speed: 1.9 },
    sound: { rootHz: 144, brightness: .57, roughness: .39, space: .36, rotationFx: .86, attack: .018, release: .32 },
    sources: ["wire", "vowel", "pulse", "bowed", "metal"], levels: [.68, .59, .55, .64, .57],
    appearance: { skin: 0.29, lighting: 0.84 }, view: { yaw: -.28, pitch: -.4, zoom: .84 }, tremor: { finger: "all", joint: "knuckle", amount: 5.6, rate: 11.2 } },
  { id: "hand-satellite-fan", label: "Satellite fan", form: "hand", pose: "source-open", motion: { id: "finger-fan", tempo: 132, amount: .98, speed: 2.9 },
    sound: { rootHz: 417, brightness: .58, roughness: .27, space: .67, rotationFx: .72, attack: .065, release: 1.1 },
    sources: ["air", "glass", "vowel", "wire", "air"], levels: [.42, .66, .72, .54, .4],
    appearance: { skin: 0.74, lighting: 0.09 }, view: { yaw: 2.74, pitch: .15, zoom: .89 }, tremor: { finger: "alternating", joint: "middle", amount: .8, rate: 8.3 } },
  { id: "foot-rubber-march", label: "Rubber march", form: "foot", pose: "open", foot: { arch: 22, twist: -14, stretch: .18 },
    motion: { id: "two-finger-walk", tempo: 126, amount: .94, speed: 2.8, elasticity: .85 },
    sound: { rootHz: 93, brightness: .69, roughness: .53, space: .16, rotationFx: .87, attack: .009, release: .19 },
    sources: ["pulse", "metal", "wire", "metal", "bowed"], levels: [.58, .63, .7, .56, .6],
    appearance: { skin: 0.36, lighting: 0.87 }, view: { yaw: -.49, pitch: .24, zoom: .86 }, tremor: { finger: "alternating", joint: "whole", amount: 15.2, rate: 19.7, rateSpread: .37, phaseSpread: .61 } },
  { id: "foot-slow-arch", label: "Slow arch", form: "foot", pose: "source-open", foot: { arch: -18, twist: 8, stretch: .25 },
    motion: { id: "squeeze-release", tempo: 42, amount: .7, speed: .5, elasticity: .32 },
    sound: { rootHz: 47, brightness: .21, roughness: .06, space: .77, rotationFx: .61, attack: .6, release: 2.4 },
    sources: ["bowed", "air", "vowel", "bowed", "reed"], levels: [.73, .38, .64, .67, .56],
    appearance: { skin: 0.24, lighting: 0.98 }, view: { yaw: .63, pitch: -.23, zoom: .91 }, tremor: { finger: "all", joint: "tip", amount: 0, rate: 2.4 } },
  { id: "foot-sole-whisper", label: "Sole whisper", form: "foot", pose: "relaxed", foot: { arch: -28, twist: -11, stretch: -.12 },
    motion: { id: "wrist-nod", tempo: 58, amount: .62, speed: 1.05, elasticity: .45 },
    sound: { rootHz: 211, brightness: .16, roughness: .03, space: .83, rotationFx: .79, attack: .42, release: 1.9 },
    sources: ["air", "reed", "air", "vowel", "bowed"], levels: [.46, .57, .43, .65, .6],
    appearance: { skin: 0.67, lighting: 0.41 }, view: { yaw: -2.63, pitch: .12, zoom: .98 }, tremor: { finger: "all", joint: "wrist", amount: 4.8, rate: .31 } },
  { id: "foot-neon-tap", label: "Neon tap", form: "foot", pose: "point", foot: { arch: 14, twist: 21, stretch: .08 },
    motion: { id: "index-tap", tempo: 207, amount: .91, speed: 2.1, elasticity: .65 },
    sound: { rootHz: 183, brightness: .91, roughness: .43, space: .14, rotationFx: .82, attack: .004, release: .11 },
    sources: ["metal", "glass", "pulse", "metal", "wire"], levels: [.59, .73, .54, .64, .55],
    appearance: { skin: 0.58, lighting: 0.79 }, view: { yaw: .88, pitch: -.15, zoom: .86 }, tremor: { finger: "index", joint: "tip", amount: .4, rate: 9 } },
  { id: "foot-corkscrew", label: "Corkscrew toes", form: "foot", pose: "source-open", foot: { arch: 26, twist: -24, stretch: .32 },
    motion: { id: "frantic-orbit", tempo: 318, amount: .78, speed: 2.5, elasticity: 1 },
    sound: { rootHz: 131, brightness: .65, roughness: .57, space: .32, rotationFx: .98, attack: .009, release: .21 },
    sources: ["wire", "vowel", "pulse", "bowed", "metal"], levels: [.67, .6, .55, .66, .59],
    appearance: { skin: 0.93, lighting: 0.67 }, view: { yaw: -1.38, pitch: .32, zoom: .92 }, tremor: { finger: "all", joint: "spread", amount: 24, rate: 47, rateSpread: .81, phaseSpread: .38 } },
  { id: "foot-padded-ripple", label: "Padded ripple", form: "foot", pose: "fan", foot: { arch: 19, twist: 10, stretch: -.16 },
    motion: { id: "ripple-close", tempo: 71, amount: .78, speed: .75, elasticity: .25 },
    sound: { rootHz: 83, brightness: .29, roughness: .08, space: .56, rotationFx: .38, attack: .31, release: 1.35 },
    sources: ["reed", "bowed", "glass", "air", "reed"], levels: [.64, .71, .56, .4, .57],
    appearance: { skin: 0.46, lighting: 0.32 }, view: { yaw: .42, pitch: -.29, zoom: 1.04 }, tremor: { finger: "all", joint: "tip", amount: .3, rate: .42 } },
  { id: "foot-beetle-step", label: "Beetle step", form: "foot", pose: "claw", foot: { arch: -16, twist: 18, stretch: .1 },
    motion: { id: "spider-walk", tempo: 97, amount: .86, speed: 1.8, elasticity: .62 },
    sound: { rootHz: 61, brightness: .53, roughness: .45, space: .24, rotationFx: .66, attack: .018, release: .28 },
    sources: ["metal", "wire", "bowed", "metal", "pulse"], levels: [.62, .67, .71, .58, .51],
    appearance: { skin: 0.82, lighting: 0.06 }, view: { yaw: -1.8, pitch: .18, zoom: .99 }, tremor: { finger: "all", joint: "middle", amount: 12.4, rate: 10.8, rateSpread: .24, phaseSpread: .83 } },
  { id: "foot-threadbare-sway", label: "Threadbare sway", form: "foot", pose: "open", foot: { arch: -9, twist: 29, stretch: .21 },
    motion: { id: "wave", tempo: 33, amount: .58, speed: .8, elasticity: .48 },
    sound: { rootHz: 123, brightness: .19, roughness: .13, space: .81, rotationFx: .91, attack: .54, release: 2.5 },
    sources: ["bowed", "air", "wire", "air", "reed"], levels: [.72, .39, .66, .41, .59],
    appearance: { skin: 0.13, lighting: 0.18 }, view: { yaw: 1.23, pitch: -.17, zoom: .95 }, tremor: { finger: "alternating", joint: "whole", amount: 19.6, rate: .64, rateSpread: .51, phaseSpread: .71 } },
  { id: "foot-fizzing-fan", label: "Fizzing fan", form: "foot", pose: "source-open", foot: { arch: 31, twist: 14, stretch: .52 },
    motion: { id: "finger-fan", tempo: 182, amount: .98, speed: 3.2, elasticity: .9 },
    sound: { rootHz: 299, brightness: .89, roughness: .73, space: .18, rotationFx: .74, attack: .005, release: .16 },
    sources: ["air", "pulse", "air", "metal", "vowel"], levels: [.49, .56, .46, .63, .69],
    appearance: { skin: 0.61, lighting: 0.47 }, view: { yaw: -.76, pitch: .36, zoom: .79 }, tremor: { finger: "all", joint: "tip", amount: 28, rate: 76, rateSpread: .9, phaseSpread: .47 } },
  { id: "foot-toe-origami", label: "Toe origami", form: "foot", pose: "pinch", foot: { arch: 43, twist: -27, stretch: -.24 },
    motion: { id: "opposition-walk", tempo: 104, amount: .81, speed: 1.2, elasticity: .55 },
    sound: { rootHz: 177, brightness: .46, roughness: .16, space: .43, rotationFx: .51, attack: .11, release: .67 },
    sources: ["vowel", "glass", "bowed", "wire", "vowel"], levels: [.66, .58, .72, .53, .62],
    appearance: { skin: 0.53, lighting: 0.54 }, view: { yaw: 2.24, pitch: .09, zoom: 1.03 }, tremor: { finger: "all", joint: "middle", amount: 0, rate: 3.1 } },
  { id: "foot-copper-skip", label: "Copper skip", form: "foot", pose: "source-open", foot: { arch: -34, twist: -19, stretch: .4 },
    motion: { id: "scatter", tempo: 491, amount: .71, speed: 1.6, elasticity: .95 },
    sound: { rootHz: 149, brightness: .79, roughness: .51, space: .09, rotationFx: .88, attack: .004, release: .095 },
    sources: ["metal", "pulse", "metal", "wire", "metal"], levels: [.65, .52, .74, .61, .57],
    appearance: { skin: 0.06, lighting: 0.12 }, view: { yaw: -.33, pitch: -.35, zoom: .83 }, tremor: { finger: "alternating", joint: "spread", amount: .75, rate: 68, rateSpread: .59, phaseSpread: .32 } },
  { id: "foot-porcelain-pendulum", label: "Porcelain pendulum", form: "foot", pose: "open", foot: { arch: 12, twist: 25, stretch: .14 },
    motion: { id: "figure-eight", tempo: 53, amount: .63, speed: .6, elasticity: .4 },
    sound: { rootHz: 251, brightness: .37, roughness: .06, space: .69, rotationFx: .47, attack: .36, release: 1.7 },
    sources: ["glass", "vowel", "air", "bowed", "glass"], levels: [.66, .63, .4, .7, .55],
    appearance: { skin: 0.71, lighting: 0.89 }, view: { yaw: 1.66, pitch: .27, zoom: .94 }, tremor: { finger: "all", joint: "tip", amount: .5, rate: .67 } },
];

// Every six neighboring choices (including the wrap) include Foot, >300 and
// <75 effective BPM, <1° tremor and ≥4° tremor. Keep Finger loom first.
const PRESET_ORDER = [
  "wire-roll", "foot-fizzing-fan", "glass-wave", "reed-beckon",
  "foot-toe-origami", "vowel-fan", "hand-five-way-stumble", "bowed-spiral",
  "foot-tin-drumming", "hand-silk-count", "vowel-opposition", "breathing-hand",
  "foot-rubber-march", "hand-satellite-fan", "point-transmission", "hand-paper-waltz",
  "foot-velvet-curl", "scattered-sparks", "hand-velvet-scissors", "foot-glass-ripple",
  "counting-air", "hand-copper-shiver", "foot-copper-skip", "hushed-palm",
  "little-machinery", "foot-beetle-step", "slow-unfurl", "hand-tin-morse",
  "low-claw", "foot-porcelain-pendulum", "metal-walk", "hand-throat-lattice",
  "foot-corkscrew", "bowed-eight", "closed-bell", "pinch-sparks",
  "foot-ankle-orbit", "hand-radio-swarm", "metal-drumming", "foot-neon-tap",
  "tangled-polyrhythm", "hand-porcelain-flicker", "foot-slow-arch", "flourish-copper",
  "foot-threadbare-sway", "orbit-frenzy", "hand-bowed-tide", "foot-sole-whisper",
  "swarming-fingers", "hand-held-current", "foot-padded-ripple", "original-grasp",
];
const freeze = value => {
  if (value && typeof value === "object") { Object.values(value).forEach(freeze); Object.freeze(value); }
  return value;
};
export function createHandPresets({ normalizeHandConfig, HAND_POSES, handPoseForForm }) {
  const originalHands = PRESET_DEFINITIONS.map(([id, label, poseId, motionId, tempo, amount, rootHz, brightness, roughness, space, attack, release, sources, speed = 1], index) => ({
    id, label, snapshot: normalizeHandConfig({
      pose: HAND_POSES.find(p => p.id === poseId).pose, view: PRESET_VIEWS[id],
      tremor: PRESET_TREMORS[id], appearance: PRESET_APPEARANCES[id],
      motion: { id: motionId, tempo, amount, speed }, sound: { rootHz, brightness, roughness, space, rotationFx: PRESET_ROTATION_FX[id], attack, release },
      voices: sources.map((source, i) => ({ source, level: source === "air" ? .43 : .56 + ((index + i) % 4) * .085, mute: false, solo: false })),
    }),
  }));
  const originalFeet = FOOT_PRESET_DEFINITIONS.map(({ id, label, pose, sources, ...config }) => ({
    id, label, snapshot: normalizeHandConfig({ ...config, form: "foot", pose: handPoseForForm(pose, "foot"),
      voices: sources.map((source, i) => ({ source, level: source === "air" ? .43 : .6 + i * .025, mute: false, solo: false })) }),
  }));
  const added = ADDED_SCENES.map(({ id, label, form, pose: poseId, foot, sources, levels, ...config }) => {
    const pose = handPoseForForm(poseId, form);
    if (form === "foot") pose.foot = { ...foot };
    return { id, label, snapshot: normalizeHandConfig({ ...config, form, pose,
      voices: sources.map((source, i) => ({ source, level: levels[i], mute: false, solo: false })) }) };
  });
  const byId = new Map([...originalHands, ...originalFeet, ...added].map(preset => [preset.id, preset]));
  return freeze(PRESET_ORDER.map(id => byId.get(id)));
}
