// Original authored startup states, moved verbatim. No preset is applied at startup.
export function createSolidInitialState() {
  return {
  solidType: "cube",
  profileSides: 4,
  profileShapeType: "polygon",
  profileStarDepth: 0.48,
  position: 0.5,
  continuousPosition: 0.5,
  speed: 0.12,
  direction: 1,
  playing: false,
  rotationX: -24,
  rotationY: 36,
  rotationZ: 8,
  rotationXPlaying: false,
  rotationYPlaying: false,
  rotationZPlaying: false,
  rotationXSpeed: 0.03,
  rotationYSpeed: 0.08,
  rotationZSpeed: 0.02,
  planeYaw: 45,
  planePitch: -22,
  planeYawPlaying: false,
  planePitchPlaying: false,
  planeYawSpeed: 0.04,
  planePitchSpeed: 0.03,
  formScaleX: 1,
  formScaleY: 1,
  formScaleZ: 1,
  formSkewX: 0,
  formSkewZ: 0,
  audio: false,
  soundMode: "sine",
  voiceLimit: 32,
  level: 0.65,
  baseFrequency: 110,
  pitchRange: 3,
  fmIndex: 3,
  fmRatio: 2,
  percussionAttack: 3,
  percussionDecay: 110,
};
}

export function createHyperInitialState() {
  return {
  shapeType: "tesseract",
  profileSides: 4,
  profileShapeType: "polygon",
  profileStarDepth: 0.48,
  position: 0.5,
  continuousPosition: 0.5,
  speed: 0.1,
  direction: 1,
  playing: false,
  rotationXW: 24,
  rotationYW: -18,
  rotationZW: 12,
  rotationXWPlaying: false,
  rotationYWPlaying: false,
  rotationZWPlaying: false,
  rotationXWSpeed: 0.06,
  rotationYWSpeed: 0.04,
  rotationZWSpeed: -0.02,
  hyperScaleX: 1,
  hyperScaleY: 1,
  hyperScaleZ: 1,
  hyperScaleW: 1,
  audio: false,
  soundMode: "sine",
  voiceLimit: 20,
  level: 0.6,
  baseFrequency: 82,
  pitchRange: 4,
  fmIndex: 3.5,
  fmRatio: 1.5,
  percussionAttack: 3,
  percussionDecay: 120,
};
}
