import { MICMIC_PRESETS, GENERATION_RULE_PRESETS, FIXED_FORK_DENSITY } from "../../micmic.js";
import { GRANULAR_ECONOMY_PITCH_CLASSES } from "../../granular-economy-renderer.js";
export const DEFAULT_L_SYSTEM_STATE = Object.freeze({
  presetId: "pythagorean",
  iterations: 7,
  angle: 45,
  turnAsymmetry: 0,
  lengthScale: 0.72,
  position: 0,
  continuousPosition: 0,
  speed: 0.3,
  direction: 1,
  traversalBehavior: "loop",
  playing: false,
  audio: false,
  level: 0.55,
  pitchSource: "angle",
  baseFrequency: 220,
  pitchRange: 2,
  depthAmount: 0.65,
  soundMode: "sine",
  modulationIndex: 3,
  stereoSpread: 0.9,
  structureMode: "final",
});
export const DEFAULT_MICMIC_STATE = Object.freeze({
  ...MICMIC_PRESETS.bloom,
  inputTrim: 0.85,
  level: 0.58,
  mic: false,
  starting: false,
  frozen: false,
  generations: GENERATION_RULE_PRESETS.pythagorean.generations,
  branching: FIXED_FORK_DENSITY,
  depth: GENERATION_RULE_PRESETS.pythagorean.depth,
  interval: GENERATION_RULE_PRESETS.pythagorean.interval,
  mutation: GENERATION_RULE_PRESETS.pythagorean.mutation,
  generationPreset: "pythagorean",
  lSystemType: "pythagorean",
  timeRatio: GENERATION_RULE_PRESETS.pythagorean.timeRatio,
  generationAngle: GENERATION_RULE_PRESETS.pythagorean.angle,
  generationAsymmetry: GENERATION_RULE_PRESETS.pythagorean.asymmetry,
  generationPitchScale: GENERATION_RULE_PRESETS.pythagorean.pitchScale,
  pruningBias: 0,
  pitchDetail: GRANULAR_ECONOMY_PITCH_CLASSES,
});
