import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import test from "node:test";

const execFileAsync = promisify(execFile);
const root = new URL("../", import.meta.url);

async function exists(path) {
  try {
    await stat(path);
    return true;
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
}

test("site builder publishes runtime files without development material", async () => {
  const temporary = await mkdtemp(join(tmpdir(), "morphazoid-site-"));
  const output = join(temporary, "public");
  try {
    await execFileAsync("node", ["scripts/build-release-site.mjs", output], {
      cwd: root,
    });

    for (const path of [
      "index.html",
      "moebius-synth.html",
      "klein-bottle-synth.html",
      "src/families/nonorientable/nonorientable.css",
      "src/families/nonorientable/nonorientable-app.js",
      "src/families/nonorientable/nonorientable-surface.js",
      "assets/instruments/moebius.webp",
      "assets/instruments/klein-bottle.webp",
      "dist-wax/moebius-synth.html",
      "dist-wax/klein-bottle-synth.html",
      "dist-wax/src/families/nonorientable/nonorientable.css",
      "dist-wax/src/families/nonorientable/nonorientable-app.js",
      "dist-wax/src/families/nonorientable/nonorientable-surface.js",
      "dist-wax/assets/instruments/moebius.webp",
      "dist-wax/assets/instruments/klein-bottle.webp",
      "midi-guide.html",
      "shapes.html",
      "shapes.html",
      "src/instruments/shapes/shapes.css",
      "src/families/geometry/shapes-embed.css",
      "src/instruments/shapes/shapes-app.js",
      "src/instruments/shapes/shapes-host.js",
      "src/instruments/shapes/shapes-state.js",
      "src/instruments/shapes/shapes-scene.js",
      "src/instruments/shapes/shapes-rhythm.js",
      "src/instruments/shapes/shapes-profile.js",
      "src/families/geometry/shapes-native-bridge.js",
      "assets/instruments/combo.webp",
      "shape-synth.html",
      "playhead-paint.html",
      "src/instruments/playhead-paint/playhead-paint.css",
      "src/instruments/playhead-paint/playhead-paint-app.js",
      "src/instruments/playhead-paint/playhead-paint.js",
      "src/instruments/playhead-paint/playhead-paint-audio.js",
      "assets/instruments/playhead-paint.webp",
      "enveloper.html",
      "src/instruments/enveloper/enveloper.css",
      "src/instruments/enveloper/enveloper-app.js",
      "src/instruments/enveloper/enveloper.js",
      "src/instruments/enveloper/enveloper-audio.js",
      "assets/instruments/enveloper.webp",
      "yoyodyne.html",
      "src/instruments/yoyodyne/yoyodyne.css",
      "src/instruments/yoyodyne/yoyodyne-app.js",
      "src/instruments/yoyodyne/yoyodyne.js",
      "src/instruments/yoyodyne/yoyodyne-audio.js",
      "assets/instruments/yoyodyne.webp",
      "alien-larynx.html",
      "src/instruments/alien-larynx/alien-larynx.css",
      "src/instruments/alien-larynx/alien-larynx-app.js",
      "src/families/tract/alien-larynx-tract-processor.js",
      "assets/instruments/alien-larynx.webp",
      "alien-larynx-architecture.html",
      "alien-larynx-signal-path.svg",
      "syrinx.html",
      "src/families/syrinx/syrinx.css",
      "src/families/syrinx/syrinx-app.js",
      "syrinx-ui.html",
      "src/instruments/syrinx-ui/syrinx-ui.css",
      "morphynx.html",
      "src/instruments/morphynx/morphynx.css",
      "src/instruments/morphynx/morphynx-app.js",
      "src/instruments/morphynx/morphynx.js",
      "assets/instruments/morphynx.webp",
      "hyper-syrinx.html",
      "src/instruments/hyper-syrinx/hyper-syrinx.css",
      "src/instruments/hyper-syrinx/hyper-syrinx-app.js",
      "assets/instruments/hyper-syrinx.webp",
      "tongued-beasts.html",
      "src/instruments/tongued-beasts/tongued-beasts.css",
      "assets/instruments/tongued-beasts.webp",
      "hybrinx.html",
      "src/instruments/hybrinx/hybrinx.css",
      "src/instruments/hybrinx/hybrinx-timeline.js",
      "assets/instruments/hybrinx.webp",
      "monstroid.html",
      "monstroid.html",
      "monstroid.html",
      "src/instruments/monstroid/monstroid.css",
      "src/instruments/monstroid/monstroid-app.js",
      "src/instruments/monstroid/monstroid-graph.js",
      "src/instruments/monstroid/monstroid.js",
      "src/instruments/monstroid/monstroid-processor.js",
      "src/families/syrinx/monstrozoid-body.js",
      "assets/instruments/colony-syrinx.webp",
      "wave-pool.html",
      "src/instruments/wave-pool/wave-pool.css",
      "src/instruments/wave-pool/wave-pool-app.js",
      "src/instruments/wave-pool/wave-pool.js",
      "src/instruments/wave-pool/wave-pool-processor.js",
      "assets/instruments/wave-pool.webp",
      "WAVE_POOL_RESEARCH.md",
      "vector-flight.html",
      "src/instruments/vector-flight/vector-flight.css",
      "src/instruments/vector-flight/vector-flight-app.js",
      "src/instruments/vector-flight/vector-flight.js",
      "assets/instruments/vector-flight.webp",
      "surround-field.html",
      "src/instruments/surround-field/surround-field.css",
      "src/instruments/surround-field/surround-field-app.js",
      "src/instruments/surround-field/surround-field.js",
      "src/instruments/surround-field/surround-field-recorder.js",
      "src/instruments/surround-field/surround-field-recorder-processor.js",
      "assets/instruments/surround-field.webp",
      "pink-trombonazoid.html",
      "src/instruments/pink-trombonazoid/pink-trombonazoid.css",
      "src/instruments/pink-trombonazoid/pink-trombonazoid-app.js",
      "src/families/tract/pink-trombonazoid.js",
      "assets/instruments/pink-trombonazoid.webp",
      "throat-singing.html",
      "src/instruments/throat-singing/throat-singing.css",
      "src/instruments/throat-singing/throat-singing-app.js",
      "src/instruments/throat-singing/throat-singing.js",
      "THROAT_SINGING_RESEARCH.md",
      "assets/instruments/throat-singing.webp",
      "src/families/syrinx/syrinx.js",
      "src/families/syrinx/syrinx-source-models.js",
      "src/families/syrinx/syrinx-processor.js",
      "harmonica.html",
      "src/instruments/harmonica/harmonica.css",
      "src/instruments/harmonica/harmonica-app.js",
      "src/instruments/harmonica/harmonica.js",
      "src/instruments/harmonica/harmonica-processor.js",
      "assets/instruments/harmonica.webp",
      "hiccup-head.html",
      "src/instruments/hiccup-head/hiccup-head.css",
      "src/instruments/hiccup-head/hiccup-head-app.js",
      "src/instruments/hiccup-head/hiccup-head.js",
      "src/instruments/hiccup-head/hiccup-head-processor.js",
      "assets/audio/hiccup-head-emt140-warm-plate.wav",
      "assets/audio/hiccup-head-york-minster-warm-hall.wav",
      "assets/audio/HICCUP_HEAD_REVERB_ATTRIBUTION.md",
      "assets/instruments/hiccup-head.webp",
      "quadruped.html",
      "quadroped.html",
      "src/instruments/quadruped/quadruped.css",
      "src/instruments/quadruped/quadruped-app.js",
      "src/instruments/quadruped/quadruped.js",
      "QUADRUPED_RESEARCH.md",
      "assets/instruments/quadruped.webp",
      "digestazoid.html",
      "src/instruments/digestazoid/digestazoid.css",
      "src/instruments/digestazoid/digestazoid-app.js",
      "src/instruments/digestazoid/digestazoid.js",
      "src/instruments/digestazoid/digestazoid-processor.js",
      "DIGESTAZOID_RESEARCH.md",
      "assets/instruments/digestazoid.webp",
      "src/families/syrinx/tongue-physics.js",
      "assets/instruments/syrinx.webp",
      "ANIMAL_VOICE_SYNTHESIS_RESEARCH.md",
      "throatazoid-architecture.html",
      "src/site/styles/throatazoid-architecture.css",
      "throatazoid-signal-path.svg",
      "gesturama.html",
      "src/instruments/gesturama/gesturama.css",
      "src/instruments/gesturama/gesturama-app.js",
      "src/instruments/gesturama/gesturama-core.js",
      "src/instruments/gesturama/gesturama-audio.js",
      "src/instruments/gesturama/gesturama-zones.js",
      "assets/instruments/gesturama.webp",
      "about.html",
      "src/site/styles/about.css",
      "THIRD_PARTY_NOTICES.md",
      "music-rooms.html",
      "src/instruments/music-rooms/music-rooms.css",
      "assets/instruments/room-lobby.webp",
      "vocal-effects-room.html",
      "assets/instruments/vocal-effects-room.webp",
      "instrument-share-room.html",
      "assets/instruments/instrument-share-room.webp",
      "morphazoid-roulette.html",
      "assets/instruments/morphazoid-roulette.webp",
      "assets/instruments/drum-roll-please.webp",
      "assets/instruments/ouroborousel.webp",
      "assets/instruments/ourorourobouroboros.webp",
      "assets/instruments/ouroboros.webp",
      "assets/instruments/ouroboros-borealis.webp",
      "assets/instruments/image-to-instrument-3.webp",
      "image-to-instrument-3.html",
      "src/families/image-to-instrument/image-to-instrument-app.js",
      "src/instruments/wheel-of-organs/wheel-of-organs-app.js",
      "src/families/image-to-instrument/image-to-instrument.css",
      "src/families/image-to-instrument/image-to-instrument.js",
      "src/instruments/wheel-of-organs/wheel-of-organs.js",
      "src/instruments/wheel-of-organs/wheel-of-organs-audio.js",
      "spelling-synthesizer.html",
      "src/instruments/spelling-synthesizer/spelling-synthesizer.css",
      "src/instruments/spelling-synthesizer/spelling-synthesizer-app.js",
      "src/instruments/spelling-synthesizer/spelling-synthesizer.js",
      "src/instruments/spelling-synthesizer/spelling-synthesizer-audio.js",
      "src/instruments/spelling-synthesizer/spelling-diphone-atlas.js",
      "src/instruments/spelling-synthesizer/spelling-pronunciation.js",
      "src/instruments/spelling-synthesizer/spelling-vocoder-processor.js",
      "assets/audio/spelling-diphone-kal16.wav",
      "assets/instruments/spelling-synthesizer.webp",
      "vocalzoid.html",
      "src/instruments/vocalzoid/vocalzoid.css",
      "src/instruments/vocalzoid/vocalzoid-app.js",
      "src/instruments/vocalzoid/vocalzoid.js",
      "src/instruments/vocalzoid/vocalzoid-audio.js",
      "src/instruments/vocalzoid/vocalzoid-bank.js",
      "src/instruments/vocalzoid/vocalzoid-open-banks.js",
      "assets/audio/vocalzoid-oddvoices-air.wav",
      "assets/audio/vocalzoid-oddvoices-cicada.wav",
      "assets/audio/vocalzoid-oddvoices-quake.wav",
      "assets/audio/vocalzoid-cmu-arctic-bdl.wav",
      "assets/audio/vocalzoid-cmu-arctic-clb.wav",
      "assets/audio/vocalzoid-cmu-arctic-jmk.wav",
      "assets/audio/vocalzoid-cmu-arctic-ksp.wav",
      "assets/audio/vocalzoid-cmu-arctic-slt.wav",
      "assets/instruments/vocalzoid.webp",
      "vendor/oddvoices/LICENSE",
      "vendor/cmu-arctic/COPYING",
      "vendor/cmu-arctic/COPYING-2005",
      "vendor/cmudict/cmudict-en-us.dict",
      "vendor/cmudict/LICENSE",
      "plugins.html",
      "src/site/plugins.css",
      "src/site/plugins-app.js",
      "src/site/plugin-catalog.js",
      "wax.html",
      "src/instruments/wax/wax.css",
      "wax-page.js",
      "src/instruments/wax/wax-instrument-roles.js",
      "src/instruments/wax/wax-midi-routing.js",
      "dist-wax/wax/wax-universal-adapter.js",
      "dist-wax/micromorph.html",
      "dist-wax/src/instruments/micromorph/micromorph.css",
      "dist-wax/src/instruments/micromorph/micromorph-app.js",
      "dist-wax/src/instruments/micromorph/micromorph.js",
      "dist-wax/src/instruments/micromorph/micromorph-model-client.js",
      "dist-wax/assets/instruments/micromorph.webp",
      "dist-wax/karplus-carpet.html",
      "dist-wax/src/instruments/karplus-carpet/karplus-carpet.css",
      "dist-wax/src/instruments/karplus-carpet/karplus-carpet-app.js",
      "dist-wax/src/instruments/karplus-carpet/karplus-carpet.js",
      "dist-wax/assets/instruments/karplus-carpet.webp",
      "dist-wax/throat-singing.html",
      "dist-wax/src/instruments/throat-singing/throat-singing.css",
      "dist-wax/src/instruments/throat-singing/throat-singing-app.js",
      "dist-wax/src/instruments/throat-singing/throat-singing.js",
      "dist-wax/THROAT_SINGING_RESEARCH.md",
      "dist-wax/assets/instruments/throat-singing.webp",
      "dist-wax/harmonica.html",
      "dist-wax/src/instruments/harmonica/harmonica.css",
      "dist-wax/src/instruments/harmonica/harmonica-app.js",
      "dist-wax/src/instruments/harmonica/harmonica.js",
      "dist-wax/src/instruments/harmonica/harmonica-processor.js",
      "dist-wax/assets/instruments/harmonica.webp",
      "dist-wax/hiccup-head.html",
      "dist-wax/src/instruments/hiccup-head/hiccup-head.css",
      "dist-wax/src/instruments/hiccup-head/hiccup-head-app.js",
      "dist-wax/src/instruments/hiccup-head/hiccup-head.js",
      "dist-wax/src/instruments/hiccup-head/hiccup-head-processor.js",
      "dist-wax/assets/audio/hiccup-head-emt140-warm-plate.wav",
      "dist-wax/assets/audio/hiccup-head-york-minster-warm-hall.wav",
      "dist-wax/assets/audio/HICCUP_HEAD_REVERB_ATTRIBUTION.md",
      "dist-wax/assets/instruments/hiccup-head.webp",
      "dist-wax/quadruped.html",
      "dist-wax/quadroped.html",
      "dist-wax/src/instruments/quadruped/quadruped.css",
      "dist-wax/src/instruments/quadruped/quadruped-app.js",
      "dist-wax/src/instruments/quadruped/quadruped.js",
      "dist-wax/QUADRUPED_RESEARCH.md",
      "dist-wax/assets/instruments/quadruped.webp",
      "dist-wax/digestazoid.html",
      "dist-wax/src/instruments/digestazoid/digestazoid.css",
      "dist-wax/src/instruments/digestazoid/digestazoid-app.js",
      "dist-wax/src/instruments/digestazoid/digestazoid.js",
      "dist-wax/src/instruments/digestazoid/digestazoid-processor.js",
      "dist-wax/DIGESTAZOID_RESEARCH.md",
      "dist-wax/assets/instruments/digestazoid.webp",
      "dist-wax/monstroid.html",
      "dist-wax/monstroid.html",
      "dist-wax/monstroid.html",
      "dist-wax/src/instruments/monstroid/monstroid.css",
      "dist-wax/src/instruments/monstroid/monstroid-app.js",
      "dist-wax/src/instruments/monstroid/monstroid-graph.js",
      "dist-wax/src/instruments/monstroid/monstroid.js",
      "dist-wax/src/instruments/monstroid/monstroid-processor.js",
      "dist-wax/src/families/syrinx/monstrozoid-body.js",
      "dist-wax/assets/instruments/colony-syrinx.webp",
      "dist-wax/wave-pool.html",
      "dist-wax/src/instruments/wave-pool/wave-pool.css",
      "dist-wax/src/instruments/wave-pool/wave-pool-app.js",
      "dist-wax/src/instruments/wave-pool/wave-pool.js",
      "dist-wax/src/instruments/wave-pool/wave-pool-processor.js",
      "dist-wax/assets/instruments/wave-pool.webp",
      "dist-wax/WAVE_POOL_RESEARCH.md",
      "dist-wax/moire-drone.html",
      "dist-wax/src/instruments/moire-drone/moire-drone.css",
      "dist-wax/src/instruments/moire-drone/moire-drone-app.js",
      "dist-wax/src/instruments/moire-drone/moire-drone.js",
      "dist-wax/assets/instruments/moire-drone.webp",
      "dist-wax/graph-drum-machine.html",
      "dist-wax/graph-synth.html",
      "dist-wax/src/families/graph/graph-instruments.css",
      "dist-wax/src/instruments/graph-drum-machine/graph-drum-machine-app.js",
      "dist-wax/src/instruments/graph-synth/graph-synth-app.js",
      "dist-wax/src/families/graph/graph-drum-audio.js",
      "dist-wax/src/families/graph/graph-instrument-app.js",
      "dist-wax/src/families/graph/graph-instruments.js",
      "dist-wax/src/families/graph/graph-synth-audio.js",
      "dist-wax/assets/instruments/graph-drums.webp",
      "dist-wax/assets/instruments/graph-synth.webp",
      "dist-wax/GRAPH_INSTRUMENTS_RESEARCH.md",
      "dist-wax/graphs.html",
      "dist-wax/src/instruments/graphs/graphs.css",
      "dist-wax/src/instruments/graphs/graphs-app.js",
      "dist-wax/src/instruments/graphs/graphs-suite.js",
      "dist-wax/src/instruments/graph-delay/graph-delay-audio.js",
      "dist-wax/assets/instruments/graphs.webp",
      "dist-wax/enveloper.html",
      "dist-wax/src/instruments/enveloper/enveloper.css",
      "dist-wax/src/instruments/enveloper/enveloper-app.js",
      "dist-wax/src/instruments/enveloper/enveloper.js",
      "dist-wax/src/instruments/enveloper/enveloper-audio.js",
      "dist-wax/assets/instruments/enveloper.webp",
      "dist-wax/yoyodyne.html",
      "dist-wax/src/instruments/yoyodyne/yoyodyne.css",
      "dist-wax/src/instruments/yoyodyne/yoyodyne-app.js",
      "dist-wax/src/instruments/yoyodyne/yoyodyne.js",
      "dist-wax/src/instruments/yoyodyne/yoyodyne-audio.js",
      "dist-wax/assets/instruments/yoyodyne.webp",
      "dist-wax/ouroborousel.html",
      "dist-wax/src/instruments/ouroborousel/ouroborousel.css",
      "dist-wax/src/instruments/ouroborousel/ouroborousel-app.js",
      "dist-wax/src/instruments/ouroborousel/ouroborousel.js",
      "dist-wax/assets/instruments/ouroborousel.webp",
      "dist-wax/ourorourobouroboros.html",
      "dist-wax/src/instruments/ourorourobouroboros/ourorourobouroboros.css",
      "dist-wax/src/instruments/ourorourobouroboros/ourorourobouroboros-app.js",
      "dist-wax/src/instruments/ourorourobouroboros/ourorourobouroboros.js",
      "dist-wax/assets/instruments/ourorourobouroboros.webp",
      "dist-wax/ouroboros.html",
      "dist-wax/src/instruments/ouroboros/ouroboros.js",
      "dist-wax/ouroboros-borealis.html",
      "dist-wax/src/instruments/ouroboros-borealis/ouroboros-borealis.css",
      "dist-wax/src/instruments/ouroboros-borealis/ouroboros-borealis-app.js",
      "dist-wax/src/instruments/ouroboros-borealis/ouroboros-borealis.js",
      "dist-wax/assets/instruments/ouroboros-borealis.webp",
      "dist-wax/src/instruments/rubix/rubix-webgpu-303.js",
      "dist-wax/webgpu-chiptune.html",
      "dist-wax/src/instruments/webgpu-chiptune/webgpu-chiptune.css",
      "dist-wax/src/instruments/webgpu-chiptune/webgpu-chiptune-app.js",
      "dist-wax/src/instruments/webgpu-chiptune/webgpu-chiptune.js",
      "dist-wax/sliding-puzzle.html",
      "dist-wax/src/instruments/sliding-puzzle/sliding-puzzle.css",
      "dist-wax/src/instruments/sliding-puzzle/sliding-puzzle-app.js",
      "dist-wax/src/instruments/sliding-puzzle/sliding-puzzle.js",
      "dist-wax/assets/instruments/sliding-puzzle.webp",
      "dist-wax/assets/instruments/ouroboros.webp",
      "dist-wax/assets/audio/spelling-diphone-kal16.wav",
      "dist-wax/vendor/signalsmith-stretch/SignalsmithStretch.mjs",
      "src/midi-manager.js",
      "src/midi-output-preview.js",
      "src/instruments/shape-synth/shape-midi.js",
      "src/instruments/fm-drums/fm-drums-midi.js",
      "sample-drums.html",
      "src/instruments/sample-drums/sample-drums.css",
      "src/instruments/sample-drums/sample-drums-app.js",
      "src/instruments/sample-drums/sample-drums.js",
      "karplus-strong.html",
      "src/instruments/karplus-strong/karplus-strong.css",
      "src/instruments/karplus-strong/karplus-strong-app.js",
      "src/instruments/karplus-strong/karplus-strong.js",
      "assets/instruments/karplus-strong.webp",
      "karplus-carpet.html",
      "src/instruments/karplus-carpet/karplus-carpet.css",
      "src/instruments/karplus-carpet/karplus-carpet-app.js",
      "src/instruments/karplus-carpet/karplus-carpet.js",
      "assets/instruments/karplus-carpet.webp",
      "downloads/plugins/chaotic-fm/0.2.1/reaper-jsfx/Morphazoid_Chaotic_FM.jsfx",
      "downloads/plugins/chaotic-fm/0.2.2/reaper-jsfx/Morphazoid_Chaotic_FM.jsfx",
      "downloads/plugins/chaotic-fm/0.2.3/reaper-jsfx/Morphazoid_Chaotic_FM.jsfx",
      "downloads/plugins/chaotic-fm/0.3.0/reaper-jsfx/Morphazoid_Chaotic_FM.jsfx",
      "src/instruments/shape-synth/shape-synth-app.js",
      "src/audio.js",
      "src/contour-synth-processor.js",
      "l-mic.html",
      "micmic.html",
      "src/instruments/micmic/micmic-app.js",
      "src/instruments/micmic/micmic.css",
      "micromorph.html",
      "src/instruments/micromorph/micromorph.css",
      "src/instruments/micromorph/micromorph-app.js",
      "src/instruments/micromorph/micromorph.js",
      "src/instruments/micromorph/micromorph-model-client.js",
      "assets/instruments/micromorph.webp",
      "shepard-risset.html",
      "src/instruments/shepard-risset/shepard-risset-app.js",
      "src/instruments/shepard-risset/shepard-risset.js",
      "slippery-resynthesis.html",
      "src/instruments/slippery-resynthesis/slippery-resynthesis.css",
      "src/instruments/slippery-resynthesis/slippery-resynthesis-app.js",
      "src/instruments/slippery-resynthesis/slippery-resynthesis.js",
      "assets/instruments/slippery-resynthesis.webp",
      "simd-resonator.html",
      "simd-lab.html",
      "src/families/simd-resonator/simd-resonator.css",
      "src/families/simd-resonator/simd-resonator-app.js",
      "src/simd-resonator.js",
      "src/simd-resonator-processor.js",
      "assets/wasm/simd-resonator-scalar.wasm",
      "assets/wasm/simd-resonator-simd.wasm",
      "assets/instruments/simd-resonator.webp",
      "simd-303.html",
      "src/instruments/simd-303/simd-303.css",
      "src/instruments/simd-303/simd-303-app.js",
      "src/simd-303.js",
      "src/simd-303-processor.js",
      "assets/wasm/simd-303-scalar.wasm",
      "assets/wasm/simd-303-simd.wasm",
      "simd-synth.html",
      "src/instruments/simd-synth/simd-synth.css",
      "src/instruments/simd-synth/simd-synth-app.js",
      "SIMD_SYNTH_RESEARCH.md",
      "src/simd-synth.js",
      "src/simd-synth-processor.js",
      "src/simd-synth-presets.js",
      "src/simd-synth-user-presets.js",
      "assets/wasm/simd-synth-scalar.wasm",
      "assets/wasm/simd-synth-simd.wasm",
      "assets/instruments/simd-synth.webp",
      "dist-wax/simd-resonator.html",
      "dist-wax/simd-lab.html",
      "dist-wax/src/families/simd-resonator/simd-resonator.css",
      "dist-wax/src/families/simd-resonator/simd-resonator-app.js",
      "dist-wax/src/simd-resonator.js",
      "dist-wax/src/simd-resonator-processor.js",
      "dist-wax/assets/wasm/simd-resonator-scalar.wasm",
      "dist-wax/assets/wasm/simd-resonator-simd.wasm",
      "dist-wax/assets/instruments/simd-resonator.webp",
      "dist-wax/simd-303.html",
      "dist-wax/src/instruments/simd-303/simd-303.css",
      "dist-wax/src/instruments/simd-303/simd-303-app.js",
      "dist-wax/src/simd-303.js",
      "dist-wax/src/simd-303-processor.js",
      "dist-wax/assets/wasm/simd-303-scalar.wasm",
      "dist-wax/assets/wasm/simd-303-simd.wasm",
      "dist-wax/simd-synth.html",
      "dist-wax/src/instruments/simd-synth/simd-synth.css",
      "dist-wax/src/instruments/simd-synth/simd-synth-app.js",
      "dist-wax/SIMD_SYNTH_RESEARCH.md",
      "dist-wax/src/simd-synth.js",
      "dist-wax/src/simd-synth-processor.js",
      "dist-wax/src/simd-synth-presets.js",
      "dist-wax/src/simd-synth-user-presets.js",
      "dist-wax/assets/wasm/simd-synth-scalar.wasm",
      "dist-wax/assets/wasm/simd-synth-simd.wasm",
      "dist-wax/assets/instruments/simd-synth.webp",
      "moire-drone.html",
      "src/instruments/moire-drone/moire-drone.css",
      "src/instruments/moire-drone/moire-drone-app.js",
      "src/instruments/moire-drone/moire-drone.js",
      "assets/instruments/moire-drone.webp",
      "drum-roll-please.html",
      "src/instruments/drum-roll-please/drum-roll-please.css",
      "src/instruments/drum-roll-please/drum-roll-please-app.js",
      "src/instruments/drum-roll-please/drum-roll-please.js",
      "ouroborousel.html",
      "src/instruments/ouroborousel/ouroborousel.css",
      "src/instruments/ouroborousel/ouroborousel-app.js",
      "src/instruments/ouroborousel/ouroborousel.js",
      "ourorourobouroboros.html",
      "src/instruments/ourorourobouroboros/ourorourobouroboros.css",
      "src/instruments/ourorourobouroboros/ourorourobouroboros-app.js",
      "src/instruments/ourorourobouroboros/ourorourobouroboros.js",
      "ouroboros.html",
      "src/instruments/ouroboros/ouroboros.css",
      "src/instruments/ouroboros/ouroboros-app.js",
      "src/instruments/ouroboros/ouroboros.js",
      "ouroboros-borealis.html",
      "src/instruments/ouroboros-borealis/ouroboros-borealis.css",
      "src/instruments/ouroboros-borealis/ouroboros-borealis-app.js",
      "src/instruments/ouroboros-borealis/ouroboros-borealis.js",
      "candy-coil-delay.html",
      "sandy-syrup-delay.html",
      "src/families/barber-delay/barber-delay.css",
      "src/families/barber-delay/barber-delay-app.js",
      "src/families/barber-delay/barber-delay.js",
      "recursive-fm.html",
      "src/instruments/recursive-fm/recursive-fm-app.js",
      "src/instruments/recursive-fm/recursive-fm.js",
      "cascading-fm.html",
      "src/instruments/cascading-fm/cascading-fm.css",
      "src/instruments/cascading-fm/cascading-fm-app.js",
      "src/instruments/cascading-fm/cascading-fm.js",
      "assets/instruments/cascading-fm.webp",
      "recursive-pm.html",
      "src/instruments/recursive-pm/recursive-pm.css",
      "src/instruments/recursive-pm/recursive-pm-app.js",
      "src/instruments/recursive-pm/recursive-pm.js",
      "src/instruments/recursive-pm/recursive-pm-midi.js",
      "cascading-pm.html",
      "src/instruments/cascading-pm/cascading-pm.css",
      "src/instruments/cascading-pm/cascading-pm-app.js",
      "src/instruments/cascading-pm/cascading-pm.js",
      "assets/instruments/cascading-pm.webp",
      "chaotic-fm.html",
      "src/instruments/chaotic-fm/chaotic-fm.css",
      "src/instruments/chaotic-fm/chaotic-fm-app.js",
      "chaotic-dsp-reference.html",
      "src/instruments/chaotic-dsp-reference/chaotic-dsp-reference.css",
      "src/site/chaotic-dsp-reference-page.js",
      "src/instruments/chaotic-fm/chaotic-fm.js",
      "src/instruments/chaotic-dsp-reference/chaotic-dsp-reference.js",
      "src/families/chaotic/chaotic-fm-flow.js",
      "chaotic-pm.html",
      "src/instruments/chaotic-pm/chaotic-pm.css",
      "src/instruments/chaotic-pm/chaotic-pm-app.js",
      "src/instruments/chaotic-pm/chaotic-pm.js",
      "webgpu-303.html",
      "src/instruments/webgpu-303/webgpu-303.css",
      "src/instruments/webgpu-303/webgpu-303-app.js",
      "src/webgpu-303.js",
      "webgpu-chiptune.html",
      "src/instruments/webgpu-chiptune/webgpu-chiptune.css",
      "src/instruments/webgpu-chiptune/webgpu-chiptune-app.js",
      "src/instruments/webgpu-chiptune/webgpu-chiptune.js",
      "webgpu-synths.html",
      "src/instruments/webgpu-synths/webgpu-synths.css",
      "src/instruments/webgpu-synths/webgpu-synths-app.js",
      "src/instruments/webgpu-synths/webgpu-synths.js",
      "srtuss.html",
      "src/instruments/srtuss/srtuss.css",
      "src/instruments/srtuss/srtuss-app.js",
      "src/instruments/srtuss/srtuss.js",
      "src/instruments/srtuss/srtuss-master.js",
      "src/instruments/srtuss/srtuss-master-shaders.js",
      "src/instruments/srtuss/srtuss-shaders-a.js",
      "src/instruments/srtuss/srtuss-shaders-b.js",
      "src/instruments/srtuss/srtuss-shaders-c.js",
      "src/instruments/srtuss/srtuss-shaders-d.js",
      "assets/srtuss/pebbles.png",
      "dist-wax/srtuss.html",
      "dist-wax/src/instruments/srtuss/srtuss.css",
      "dist-wax/src/instruments/srtuss/srtuss-app.js",
      "dist-wax/src/instruments/srtuss/srtuss.js",
      "dist-wax/src/instruments/srtuss/srtuss-master.js",
      "dist-wax/src/instruments/srtuss/srtuss-master-shaders.js",
      "dist-wax/src/instruments/srtuss/srtuss-shaders-a.js",
      "dist-wax/src/instruments/srtuss/srtuss-shaders-b.js",
      "dist-wax/src/instruments/srtuss/srtuss-shaders-c.js",
      "dist-wax/src/instruments/srtuss/srtuss-shaders-d.js",
      "dist-wax/assets/srtuss/pebbles.png",
      "webgpu-dsp-primitives.html",
      "src/instruments/webgpu-dsp-primitives/webgpu-dsp-primitives.css",
      "src/instruments/webgpu-dsp-primitives/webgpu-dsp-primitives-app.js",
      "src/instruments/webgpu-dsp-primitives/webgpu-dsp-primitives.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-primitive-coverage.js",
      "shader-synth-playground.html",
      "src/instruments/shader-synth-playground/shader-synth-playground.css",
      "src/instruments/shader-synth-playground/shader-synth-playground-app.js",
      "src/instruments/shader-synth-playground/shader-synth-playground.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-audio-assets.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-extra.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-atlas.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-atlas-routing.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-stateful.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-state-engine.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-visual-state.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-advanced-state.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-advanced-state-engine.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-found-sounds.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-fx.js",
      "src/instruments/shader-synth-playground/shader-synth-playground-scenes.js",
      "assets/instruments/webgpu-synths.webp",
      "weierstrass.html",
      "src/instruments/weierstrass/weierstrass.css",
      "src/instruments/weierstrass/weierstrass-app.js",
      "src/instruments/weierstrass/weierstrass.js",
      "algorithmic-sequencers.html",
      "src/families/algorithmic-sequencers/algorithmic-sequencers.css",
      "src/families/algorithmic-sequencers/algorithmic-sequencers-app.js",
      "src/families/algorithmic-sequencers/algorithmic-sequencers.js",
      "algorithmic-scores.html",
      "src/families/algorithmic-scores/algorithmic-scores.css",
      "src/families/algorithmic-scores/algorithmic-scores-app.js",
      "src/families/algorithmic-scores/algorithmic-scores.js",
      "dijkstra.html",
      "hanoi.html",
      "minimax.html",
      "nqueens.html",
      "euclid.html",
      "gravity-walk.html",
      "ricochet.html",
      "rigidity.html",
      "rolling-measure.html",
      "falling-forms.html",
      "charge-garden.html",
      "packing-pressure.html",
      "geodesic-drift.html",
      "kinetic-hull.html",
      "src/families/physics/physics.css",
      "src/families/physics/physics-app.js",
      "src/families/physics/physics-common.js",
      "src/families/physics/physics-scenes-shape.js",
      "src/families/physics/physics-scenes-advanced.js",
      "src/families/physics/physics-scenes.js",
      "src/instruments/quantum-synths/quantum-synths.css",
      "order-tones.html",
      "src/instruments/order-tones/order-tones-app.js",
      "src/instruments/order-tones/order-tones.js",
      "bell-square.html",
      "src/instruments/bell-square/bell-square-app.js",
      "src/instruments/bell-square/bell-square.js",
      "quantum-square-dance.html",
      "src/instruments/quantum-square-dance/quantum-square-dance-app.js",
      "src/instruments/quantum-square-dance/quantum-square-dance.js",
      "assets/instruments/quantum-square-dance.webp",
      "annealogue.html",
      "src/instruments/annealogue/annealogue-app.js",
      "src/instruments/annealogue/annealogue.js",
      "src/instruments/fractal-uncertainty/fractal-uncertainty.css",
      "cantor-lock.html",
      "src/instruments/cantor-lock/cantor-lock-app.js",
      "src/instruments/cantor-lock/cantor-lock.js",
      "assets/instruments/cantor-lock.webp",
      "escape-dust.html",
      "src/instruments/escape-dust/escape-dust-app.js",
      "src/instruments/escape-dust/escape-dust.js",
      "assets/instruments/escape-dust.webp",
      "linebreaker.html",
      "src/instruments/linebreaker/linebreaker-app.js",
      "src/instruments/linebreaker/linebreaker.js",
      "assets/instruments/linebreaker.webp",
      "plasma-ball.html",
      "src/instruments/plasma-ball/plasma-ball.css",
      "src/instruments/plasma-ball/plasma-ball-app.js",
      "src/instruments/plasma-ball/plasma-ball.js",
      "assets/instruments/plasma-ball.webp",
      "moire-organ.html",
      "chladni-plate.html",
      "spring-choir.html",
      "gear-ratio-drums.html",
      "automatapoeia.html",
      "automatopoeia.html",
      "automata.html",
      "cellular-automata.html",
      "prime-sieve.html",
      "lissajous-orbits.html",
      "pendulum-wave.html",
      "double-pendulum.html",
      "reaction-diffusion.html",
      "atomic-orbitals.html",
      "dna-translator.html",
      "neural-pulse.html",
      "fourier-epicycles.html",
      "gravity-lens.html",
      "orbital-ferris.html",
      "src/families/experiments/experiments.css",
      "src/families/experiments/experiments-app.js",
      "src/instruments/cellular-automata/automatapoeia.js",
      "src/instruments/orbital-ferris/orbital-ferris.js",
      "assets/instruments/orbital-ferris.webp",
      "mouthophones.html",
      "l-systems.html",
      "src/instruments/l-systems/l-systems.css",
      "src/instruments/l-systems/l-systems-app.js",
      "src/instruments/l-systems/l-systems-suite.js",
      "assets/instruments/l-systems.webp",
      "graphs.html",
      "src/instruments/graphs/graphs.css",
      "src/instruments/graphs/graphs-app.js",
      "src/instruments/graphs/graphs-suite.js",
      "src/instruments/graph-delay/graph-delay-audio.js",
      "assets/instruments/graphs.webp",
      "algorithmic-mazes.html",
      "src/instruments/algorithmic-mazes/algorithmic-mazes.css",
      "src/instruments/algorithmic-mazes/algorithmic-mazes-app.js",
      "src/instruments/algorithmic-mazes/algorithmic-mazes.js",
      "assets/instruments/algorithmic-mazes.webp",
      "paths.html",
      "src/instruments/paths/paths.css",
      "src/instruments/paths/paths-app.js",
      "src/instruments/paths/paths.js",
      "assets/instruments/paths.webp",
      "shape-drum-machine.html",
      "src/instruments/shape-drum-machine/shape-drum-machine.css",
      "src/instruments/shape-drum-machine/shape-drum-machine-app.js",
      "src/instruments/shape-drum-machine/shape-drum-machine.js",
      "escher-tessellation.html",
      "src/instruments/escher-tessellation/escher-tessellation.css",
      "src/instruments/escher-tessellation/escher-tessellation-app.js",
      "src/instruments/escher-tessellation/escher-tessellation.js",
      "src/instruments/escher-tessellation/escher-contours.js",
      "src/instruments/escher-tessellation/escher-performance-audio.js",
      "assets/instruments/escher-tessellation.webp",
      "penrose-tilings.html",
      "src/instruments/penrose-tilings/penrose-tilings.css",
      "src/instruments/penrose-tilings/penrose-tilings-app.js",
      "src/instruments/penrose-tilings/penrose-tilings.js",
      "assets/instruments/penrose-tilings.webp",
      "solid-drum-machine.html",
      "src/instruments/solid-drum-machine/solid-drum-machine.css",
      "src/instruments/solid-drum-machine/solid-drum-machine-app.js",
      "src/instruments/solid-drum-machine/solid-drum-machine.js",
      "rubix.html",
      "src/instruments/rubix/rubix.css",
      "src/instruments/rubix/rubix-app.js",
      "src/instruments/rubix/rubix.js",
      "src/instruments/rubix/rubix-webgpu-303.js",
      "src/instruments/rubix/rubix-visibility.js",
      "assets/instruments/rubix.webp",
      "sliding-puzzle.html",
      "src/instruments/sliding-puzzle/sliding-puzzle.css",
      "src/instruments/sliding-puzzle/sliding-puzzle-app.js",
      "src/instruments/sliding-puzzle/sliding-puzzle.js",
      "assets/instruments/sliding-puzzle.webp",
      "hyper-rubix.html",
      "src/instruments/hyper-rubix/hyper-rubix.css",
      "src/instruments/hyper-rubix/hyper-rubix-app.js",
      "src/instruments/hyper-rubix/hyper-rubix.js",
      "src/instruments/hyper-rubix/hyper-rubix-webgpu-303.js",
      "assets/instruments/hyper-rubix.webp",
      "hyper-drum-machine.html",
      "src/instruments/hyper-drum-machine/hyper-drum-machine.css",
      "src/instruments/hyper-drum-machine/hyper-drum-machine-app.js",
      "src/instruments/hyper-drum-machine/hyper-drum-machine.js",
      "l-system-drum-machine.html",
      "src/instruments/l-system-drum-machine/l-system-drum-machine.css",
      "src/instruments/l-system-drum-machine/l-system-drum-machine-app.js",
      "src/instruments/l-system-drum-machine/l-system-drum-machine.js",
      "graph-drum-machine.html",
      "graph-synth.html",
      "src/families/graph/graph-instruments.css",
      "src/instruments/graph-drum-machine/graph-drum-machine-app.js",
      "src/instruments/graph-synth/graph-synth-app.js",
      "src/families/graph/graph-drum-audio.js",
      "src/families/graph/graph-instrument-app.js",
      "src/families/graph/graph-instruments.js",
      "src/families/graph/graph-synth-audio.js",
      "assets/instruments/graph-drums.webp",
      "assets/instruments/graph-synth.webp",
      "GRAPH_INSTRUMENTS_RESEARCH.md",
      "linear-drums.html",
      "src/instruments/linear-drums/linear-drums.css",
      "src/instruments/linear-drums/linear-drums-app.js",
      "src/instruments/linear-drums/linear-drums.js",
      "karplus-strong.html",
      "src/instruments/karplus-strong/karplus-strong.css",
      "src/instruments/karplus-strong/karplus-strong-app.js",
      "src/instruments/karplus-strong/karplus-strong.js",
      "assets/instruments/karplus-strong.webp",
      "karplus-carpet.html",
      "src/instruments/karplus-carpet/karplus-carpet.css",
      "src/instruments/karplus-carpet/karplus-carpet-app.js",
      "src/instruments/karplus-carpet/karplus-carpet.js",
      "assets/instruments/karplus-carpet.webp",
      "rattlesnake-skin.html",
      "src/instruments/rattlesnake-skin/rattlesnake-skin.css",
      "src/instruments/rattlesnake-skin/rattlesnake-skin-app.js",
      "src/instruments/rattlesnake-skin/linear-drums-machine.js",
      "assets/lumber-loops-wood-loop.webp",
      "morphazoidical/index.html",
      "morphazoidical/PLAN.md",
      "vendor/signalsmith-stretch/LICENSE",
      "vendor/signalsmith-stretch/SignalsmithStretch.mjs",
      "vendor/tactile/tactile.js",
      "dist-wax/index.html",
      "dist-wax/midi-guide.html",
      "dist-wax/chaotic-fm.html",
      "dist-wax/wax.html",
      "dist-wax/wax/wax-host-bootstrap.js",
      "dist-wax/wax/wax-host-bridge.js",
    ]) {
      assert.equal(await exists(join(output, path)), true, `missing ${path}`);
    }

    const publishedNavigation = await readFile(join(output, "nav.js"), "utf8");
    assert.match(
      publishedNavigation,
      /from "\.\/src\/midi-manager\.js"/,
      "the published navigation must resolve its shared MIDI manager import",
    );

    const waxInstrument = await readFile(join(output, "dist-wax", "chaotic-fm.html"), "utf8");
    assert.match(waxInstrument, /data-morphazoid-wax-bootstrap/);
    assert.equal(
      await exists(join(output, "dist-wax", "dist-wax")),
      false,
      "the WAX artifact must not recursively contain a previous WAX artifact",
    );

    const publishedNotices = await readFile(
      join(output, "THIRD_PARTY_NOTICES.md"),
      "utf8",
    );
    assert.match(
      publishedNotices,
      /CMU Flite \/ KAL16 diphone voice/,
      "the packaged sample atlas must travel with its full third-party notice",
    );
    assert.match(
      publishedNotices,
      /PocketSphinx English pronunciation dictionary/,
      "the packaged pronunciation dictionary must travel with its full third-party notice",
    );

    for (const path of [
      "tests",
      ".github",
      ".storybook",
      "stories",
      "storybook-static",
      "scripts",
      "package.json",
      "README.md",
      ".preview-cdp.ps1",
      ".throatazoid-preview.png",
      "audio-engine-lab.html",
      "src/audio-engine-lab.js",
      "analyzer.html",
      "analyzer-app.js",
      "src/analyzer.js",
      "assets/instruments/image-to-instrument-1.webp",
      "assets/instruments/image-to-instrument-2.webp",
      "image-to-instrument-1.html",
      "image-to-instrument-2.html",
      "striped-sludge-delay.html",
    ]) {
      assert.equal(await exists(join(output, path)), false, `published ${path}`);
    }
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
});

test("AWS deploy helper builds the complete default artifact and rejects missing explicit artifacts", async () => {
  const temporary = await mkdtemp(join(tmpdir(), "morphazoid-deploy-helper-"));
  const scriptsDirectory = join(temporary, "scripts");
  const binDirectory = join(temporary, "bin");
  const callLog = join(temporary, "calls.log");

  try {
    await Promise.all([
      mkdir(scriptsDirectory, { recursive: true }),
      mkdir(binDirectory, { recursive: true }),
    ]);
    await Promise.all([
      readFile(new URL("../scripts/deploy-aws-site.sh", import.meta.url), "utf8").then((source) => (
        writeFile(join(scriptsDirectory, "deploy-aws-site.sh"), source, "utf8")
      )),
      writeFile(
        join(binDirectory, "npm"),
        [
          "#!/usr/bin/env bash",
          "set -euo pipefail",
          "printf 'npm %s\\n' \"$*\" >> \"$TEST_LOG\"",
          "if [[ \"$*\" = \"run build:deploy\" ]]; then",
          "  mkdir -p \"$PWD/dist/storybook\"",
          "  touch \"$PWD/dist/storybook/index.html\"",
          "  touch \"$PWD/dist/storybook/iframe.html\"",
          "  touch \"$PWD/dist/storybook/index.json\"",
          "fi",
          "",
        ].join("\n"),
        { mode: 0o755 },
      ),
      writeFile(
        join(binDirectory, "aws"),
        [
          "#!/usr/bin/env bash",
          "set -euo pipefail",
          "printf 'aws %s\\n' \"$*\" >> \"$TEST_LOG\"",
          "",
        ].join("\n"),
        { mode: 0o755 },
      ),
    ]);

    const environment = {
      ...process.env,
      PATH: `${binDirectory}:${process.env.PATH}`,
      TEST_LOG: callLog,
      AWS_PROFILE: "",
      AWS_SITE_BUCKET: "test-site-bucket",
      AWS_CLOUDFRONT_DISTRIBUTION_ID: "TESTDISTRIBUTION",
      DRY_RUN: "true",
    };

    const defaultRun = await execFileAsync("bash", ["scripts/deploy-aws-site.sh"], {
      cwd: temporary,
      env: environment,
    });
    assert.match(defaultRun.stdout, /Dry run complete/);
    assert.equal(await exists(join(temporary, "dist")), true);

    const initialCalls = await readFile(callLog, "utf8");
    assert.match(initialCalls, /^npm run build:deploy$/m);
    assert.match(initialCalls, /^aws s3 sync /m);
    assert.ok(
      initialCalls.indexOf("npm run build:deploy") < initialCalls.indexOf("aws s3 sync"),
      "the complete deployment build must finish before the S3 sync",
    );

    await assert.rejects(
      execFileAsync("bash", ["scripts/deploy-aws-site.sh", "missing-custom-artifact"], {
        cwd: temporary,
        env: environment,
      }),
      (error) => {
        assert.equal(error.code, 1);
        assert.match(error.stderr, /Artifact directory does not exist:/);
        assert.match(error.stderr, /npm run build:deploy/);
        return true;
      },
    );
    assert.equal(
      await readFile(callLog, "utf8"),
      initialCalls,
      "a missing explicit artifact must fail before npm or AWS is invoked",
    );

    const incompleteArtifact = join(temporary, "incomplete-artifact");
    await mkdir(incompleteArtifact);
    await assert.rejects(
      execFileAsync("bash", ["scripts/deploy-aws-site.sh", incompleteArtifact], {
        cwd: temporary,
        env: environment,
      }),
      (error) => {
        assert.equal(error.code, 1);
        assert.match(error.stderr, /Artifact is incomplete: missing storybook\/index\.html/);
        return true;
      },
    );
    assert.equal(
      await readFile(callLog, "utf8"),
      initialCalls,
      "an incomplete explicit artifact must fail before AWS is invoked",
    );
  } finally {
    await rm(temporary, { recursive: true, force: true });
  }
});

test("AWS bootstrap instructions install locked dependencies before building", async () => {
  const bootstrap = await readFile(
    new URL("../scripts/bootstrap-aws-site.sh", import.meta.url),
    "utf8",
  );
  const instructions = bootstrap.slice(bootstrap.indexOf("Then publish once locally:"));

  assert.match(instructions, /npm ci/);
  assert.match(instructions, /npm run build:deploy/);
  assert.ok(instructions.indexOf("npm ci") < instructions.indexOf("npm run build:deploy"));
});

test("CloudFormation keeps the origin private and CI permissions narrow", async () => {
  const template = await readFile(new URL("../infra/site.yml", import.meta.url), "utf8");

  assert.match(template, /BlockPublicAcls:\s+true/);
  assert.match(template, /ObjectOwnership:\s+BucketOwnerEnforced/);
  assert.match(template, /SigningBehavior:\s+always/);
  assert.match(template, /OriginAccessControlId:/);
  assert.match(template, /ValidationMethod:\s+DNS/);
  assert.match(template, /HostedZoneId:\s+Z2FDTNDATAQYW2/);
  assert.match(template, /Type:\s+AAAA/);
  assert.match(template, /Runtime:\s+cloudfront-js-2\.0/);
  assert.match(template, /request\.uri\.endsWith\('\/'\)/);
  assert.match(template, /request\.uri === '\/storybook'/);
  assert.match(template, /token\.actions\.githubusercontent\.com:sub:\s+!Ref GitHubOidcSubject/);
  assert.match(template, /Header:\s+Permissions-Policy/);
  assert.match(template, /Value:\s+microphone=\(self\), camera=\(self\), geolocation=\(\)/);
  assert.match(template, /PathPattern:\s+\/storybook\/\*/);
  assert.match(template, /ResponseHeadersPolicyId:\s+!Ref StorybookSecurityHeaders/);
  assert.match(template, /FrameOption:\s+SAMEORIGIN/);
  assert.match(template, /ContentSecurityPolicy:\s+"frame-ancestors 'self'"/);
  assert.match(template, /FrameOption:\s+DENY/);
  assert.match(template, /Sid:\s+DenyInsecureTransport/);
  assert.match(template, /cloudfront:CreateInvalidation/);
  assert.doesNotMatch(template, /PolicyName:[\s\S]*?route53:\*/);
  assert.doesNotMatch(template, /PolicyName:[\s\S]*?iam:\*/);
});

test("AWS workflow verifies before OIDC deployment and uses repository variables", async () => {
  const workflow = await readFile(new URL("../.github/workflows/deploy-aws.yml", import.meta.url), "utf8");
  const preflightStart = workflow.indexOf("- name: Verify CloudFront is ready for Storybook");
  const publishStart = workflow.indexOf("- name: Publish static files");
  const s3SyncStart = workflow.indexOf("aws s3 sync");

  assert.match(workflow, /pull_request:/);
  assert.match(workflow, /push:\s*\n\s+branches:\s+\[main\]/);
  assert.match(workflow, /npm ci/);
  assert.match(workflow, /npm run verify/);
  assert.match(workflow, /npm run build:deploy/);
  assert.match(workflow, /npm run check:storybook-dist/);
  assert.match(workflow, /actions\/upload-artifact@v7/);
  assert.match(workflow, /actions\/download-artifact@v8/);
  assert.match(workflow, /aws-actions\/configure-aws-credentials@v6\.2\.3/);
  assert.match(workflow, /id-token:\s+write/);
  assert.match(workflow, /environment:\s*\n\s*#?\s*name:\s+production/);
  assert.match(workflow, /github\.ref == 'refs\/heads\/main'/);
  assert.match(workflow, /vars\.AWS_ACCOUNT_ID/);
  assert.match(workflow, /allowed-account-ids:\s+\$\{\{\s+vars\.AWS_ACCOUNT_ID\s+\}\}/);
  assert.match(workflow, /vars\.AWS_DEPLOY_ROLE_ARN/);
  assert.match(workflow, /vars\.AWS_SITE_BUCKET/);
  assert.match(workflow, /vars\.AWS_CLOUDFRONT_DISTRIBUTION_ID/);
  assert.ok(preflightStart >= 0, "the deploy job must include the CloudFront preflight");
  assert.ok(
    preflightStart < publishStart && preflightStart < s3SyncStart,
    "the CloudFront policy preflight must finish before any S3 publication",
  );
  const preflight = workflow.slice(preflightStart, publishStart);
  assert.match(preflight, /https:\/\/morphazoid\.com\/storybook\/__cloudfront-policy-probe__/);
  assert.match(preflight, /probe object is intentionally/);
  assert.match(preflight, /x-frame-options:[^\n]*DENY/i);
  assert.match(preflight, /x-frame-options:[^\n]*SAMEORIGIN/i);
  assert.match(preflight, /content-security-policy:[^\n]*frame-ancestors/i);
  const probeUrlIndex = preflight.indexOf("__cloudfront-policy-probe__");
  const probeCurlStart = preflight.lastIndexOf("curl ", probeUrlIndex);
  const probeCurl = preflight.slice(probeCurlStart, probeUrlIndex);
  assert.ok(probeCurlStart >= 0, "the Storybook preflight must make an HTTP request");
  assert.match(probeCurl, /--head/);
  assert.doesNotMatch(
    probeCurl,
    /--fail/,
    "an intentionally absent Storybook probe object must not fail on its HTTP status",
  );
  assert.match(workflow, /cloudfront wait invalidation-completed/);
  assert.match(workflow, /https:\/\/morphazoid\.com\/morphazoidical\//);
  assert.match(workflow, /https:\/\/morphazoid\.com\/storybook\//);
  assert.match(workflow, /https:\/\/morphazoid\.com\/storybook\/iframe\.html/);
  assert.match(workflow, /https:\/\/morphazoid\.com\/storybook\/index\.json/);
  assert.match(workflow, /x-frame-options:[^\n]*DENY/i);
  assert.match(workflow, /x-frame-options:[^\n]*SAMEORIGIN/i);
  assert.match(workflow, /content-security-policy:[^\n]*frame-ancestors/i);
  assert.doesNotMatch(workflow, /AWS_ACCESS_KEY_ID|AWS_SECRET_ACCESS_KEY/);
});
