import { EXTENDED_ENGINES } from '../../families/speech/extended-engines.js';
// Dates describe the cited technique or engine milestone, not this instrument.
export const VOICE_METHODS = Object.freeze({
  ...EXTENDED_ENGINES,
  ...Object.fromEntries(['slt', 'awb', 'rms'].map(voice => [`flite-${voice}`, {
    family: 'Statistical parametric synthesis', date: '2006 Clustergen paper',
    detail: `Flite's ${voice.toUpperCase()} statistical voice predicts acoustic parameters and resynthesizes speech through an MLSA vocoder. Generated locally with WebAssembly.`,
    history: 'Clustergen was published in 2006. These three speaker models share that synthesis method; they are not three independent techniques.',
    source: 'https://www.isca-archive.org/interspeech_2006/black06_interspeech.html',
  }])),
  espeak: { family: 'Formant synthesis', date: '1995 roots · 2015 NG fork',
    detail: 'eSpeak NG generates phonemes locally from a rule-based formant model. Held vowels loop inside the generated sound.',
    history: 'Speak began on RISC OS in 1995; eSpeak followed in the mid-2000s. The NG fork began in late 2015.',
    source: 'https://github.com/espeak-ng/espeak-ng#history' },
  'espeak-klatt': { family: 'Cascade / parallel formants', date: '1980 publication',
    detail: 'The Klatt synthesizer inside eSpeak NG. Compare its resonator model with eSpeak’s regular formant voice.',
    history: 'Klatt published the cascade/parallel synthesizer in 1980. This is eSpeak’s implementation, not DECtalk.',
    source: 'https://doi.org/10.1121/1.383940' },
  tube: { family: 'Articulatory synthesis', date: '2017 Pink Trombone',
    detail: 'Pinkazoid models a glottal source and a changing vocal tract. Personality changes pitch, breath and voice body.',
    history: 'Uses Morphazoid’s Throatazoid engine and a Pink Trombone-style source/tract. Articulatory synthesis predates this software.',
    source: 'https://dood.al/pinktrombone/' },
  bell: { family: 'Articulatory synthesis', date: '1961 demonstration',
    detail: 'A Kelly–Lochbaum scattering-tube model with authored phoneme shapes and glottal excitation.',
    history: 'The 1961 Bell Labs singing demonstration is a historical reference. This is an educational model, not its recording or original program.',
    source: 'https://www.dsprelated.com/freebooks/pasp/Voice_Synthesis.html' },
  diphone: { family: 'Sample concatenation', date: '2001 Flite release',
    detail: 'KAL phoneme and pair samples rendered from Flite’s KAL16 voice. Tone filters the samples; it does not replace the recorded speaker.',
    history: 'Flite was released in 2001. Diphone concatenation is older; this demo plays a prepared phone atlas, not a live Flite text engine.',
    source: 'https://github.com/festvox/flite' },
  vocoder: { family: 'Channel vocoding', date: '1939 publication',
    detail: 'Twenty analysis bands follow KAL speech and shape synthesized pulse/noise carriers.',
    history: 'Homer Dudley’s vocoder was developed at Bell Labs in the 1930s. This is a modern digital channel-vocoder demonstration.',
    source: 'https://doi.org/10.1121/1.1915976' },
  lpc: { family: 'Linear predictive synthesis', date: '1978 Speak & Spell',
    detail: 'An 8 kHz, ten-stage LPC lattice resynthesizes quantized speech coefficients with pulse/noise excitation.',
    history: 'LPC predates the 1978 Speak & Spell. This educational implementation uses KAL-derived coefficients, not TI ROM or chip emulation.',
    source: 'https://patents.google.com/patent/US4209836A/en' },
});
