/**
 * Canonical public HTML routes.
 *
 * Page source lives beside this file; the release build emits each page at the
 * site root using its route name. Keeping the route separate from its source
 * location makes the authored layout private while preserving public URLs.
 */
export const PAGE_SOURCE_DIRECTORY = "src/pages";

export const CANONICAL_PAGE_ROUTES = Object.freeze([
  "acoustic-manifold.html",
  "adaptive-airway.html",
  "algorithmic-mazes.html",
  "algorithmic-sequencers.html",
  "alien-larynx-architecture.html",
  "alien-larynx.html",
  "annealogue.html",
  "atomic-orbitals.html",
  "automatapoeia.html",
  "bell-square.html",
  "bifurcator.html",
  "birdsong-lab.html",
  "blowhole.html",
  "boidzoid.html",
  "candy-coil-delay.html",
  "cantor-lock.html",
  "cascading-fm.html",
  "cascading-pm.html",
  "chaotic-dsp-reference.html",
  "chaotic-fm.html",
  "chaotic-pm.html",
  "charge-garden.html",
  "chladni-plate.html",
  "crab-loom.html",
  "creaturazoid.html",
  "crickets.html",
  "dentaphone.html",
  "digestazoid.html",
  "dijkstra.html",
  "domino-run.html",
  "dna-translator.html",
  "double-pendulum.html",
  "drum-roll-please.html",
  "entanglement-dance.html",
  "enveloper.html",
  "escape-dust.html",
  "escher-tessellation.html",
  "euclid.html",
  "exceptional.html",
  "falling-forms.html",
  "fm-drums.html",
  "fourier-epicycles.html",
  "freeze-point.html",
  "fractal-synthesis.html",
  "gear-ratio-drums.html",
  "geodesic-drift.html",
  "gesticules.html",
  "gesturama.html",
  "graph-3d.html",
  "graph-delay.html",
  "graph-drum-machine.html",
  "graph-synth.html",
  "graphs.html",
  "gravity-lens.html",
  "gravity-walk.html",
  "habit-habitat.html",
  "hanoi.html",
  "harmonica.html",
  "head-shed.html",
  "hiccup-head.html",
  "hocket-loom.html",
  "hollowphonic.html",
  "hybrinx.html",
  "hyper-drum-machine.html",
  "hyper-rubix.html",
  "hyper-synth.html",
  "hyper-syrinx.html",
  "image-to-instrument-3.html",
  "index.html",
  "instrument-share-room.html",
  "jaw-harp.html",
  "jaw-jam.html",
  "julia.html",
  "julie-saw.html",
  "karplus-carpet.html",
  "karplus-strong.html",
  "kinetic-hull.html",
  "klein-bottle-synth.html",
  "l-mic-rust.html",
  "l-mic.html",
  "l-system-drum-machine.html",
  "l-system.html",
  "l-systems.html",
  "lattice-drum-machine.html",
  "lattice.html",
  "linear-drums.html",
  "linebreaker.html",
  "lissajous-orbits.html",
  "loop-soup.html",
  "loopini.html",
  "lumber.html",
  "micromorph.html",
  "midi-guide.html",
  "midi.html",
  "minimax.html",
  "moebius-synth.html",
  "moire-drone.html",
  "moire-organ.html",
  "monstroid.html",
  "morphazoid-roulette.html",
  "morphynx.html",
  "mouthophones.html",
  "music-rooms.html",
  "neural-pulse.html",
  "nightingale-manifold.html",
  "nqueens.html",
  "onset-atlas.html",
  "orbital-ferris.html",
  "order-tones.html",
  "ouroboros-borealis.html",
  "ouroboros.html",
  "ouroborousel.html",
  "ourorourobouroboros.html",
  "packing-pressure.html",
  "paths.html",
  "pendulum-wave.html",
  "penrose-tilings.html",
  "pink-trombonazoid.html",
  "plasma-ball.html",
  "playhead-paint.html",
  "plugins.html",
  "prime-sieve.html",
  "puggler.html",
  "quadruped.html",
  "quantum-square-dance.html",
  "rattlesnake-skin.html",
  "reaction-diffusion.html",
  "recursion.html",
  "recursive-fm.html",
  "recursive-pm.html",
  "ricochet.html",
  "rigidity.html",
  "roach-synth.html",
  "rolling-measure.html",
  "rubix.html",
  "rubixoids.html",
  "sample-drums.html",
  "sandy-syrup-delay.html",
  "scatter-ghost.html",
  "settings.html",
  "shader-synth-playground.html",
  "shape-drum-machine.html",
  "shape-synth.html",
  "shapes.html",
  "shepard-risset.html",
  "simd-303.html",
  "simd-chiptune.html",
  "simd-lab.html",
  "simd-resonator.html",
  "simd-synth.html",
  "sliding-puzzle.html",
  "slippery-resynthesis.html",
  "solid-drum-machine.html",
  "solid-synth.html",
  "spelling-synthesizer.html",
  "spider-synth.html",
  "spiral-drum-machine.html",
  "spiral.html",
  "splice-ring.html",
  "spring-choir.html",
  "srtuss.html",
  "striped-staircase.html",
  "surround-field.html",
  "synaptic-resonance.html",
  "synthesis.html",
  "synthesaurus-reference.html",
  "syrinx-ui.html",
  "syrinx.html",
  "tape-worm.html",
  "tempo-tantrum.html",
  "tesselation.html",
  "throat-singing.html",
  "throatazoid-architecture.html",
  "throatazoid.html",
  "tongued-beasts.html",
  "vector-flight.html",
  "vocal-effects-room.html",
  "vocalzoid.html",
  "voicesaurus.html",
  "wasm-garden.html",
  "wave-pool.html",
  "webgpu-303.html",
  "webgpu-chiptune.html",
  "webgpu-dsp-primitives.html",
  "webgpu-synths.html",
  "weierstrass.html",
  "yoyodyne.html",
]);

const routeSet = new Set(CANONICAL_PAGE_ROUTES);

if (routeSet.size !== CANONICAL_PAGE_ROUTES.length) {
  throw new Error("Canonical page routes must be unique");
}

for (const route of CANONICAL_PAGE_ROUTES) {
  if (!/^[a-z0-9][a-z0-9-]*\.html$/.test(route)) {
    throw new Error(`Invalid canonical page route: ${route}`);
  }
}

export function pageSourcePath(route) {
  if (!routeSet.has(route)) throw new Error(`Unknown canonical page route: ${route}`);
  return `${PAGE_SOURCE_DIRECTORY}/${route}`;
}

export function pageRouteForSourcePath(sourcePath) {
  const normalized = String(sourcePath).replaceAll("\\", "/");
  if (!normalized.startsWith(`${PAGE_SOURCE_DIRECTORY}/`)) return null;
  const route = normalized.slice(PAGE_SOURCE_DIRECTORY.length + 1);
  return routeSet.has(route) ? route : null;
}
